export * from './aPIAuthentication.service';
import { APIAuthenticationService } from './aPIAuthentication.service';
export * from './aPIFileStorage.service';
import { APIFileStorageService } from './aPIFileStorage.service';
export * from './aPIPartners.service';
import { APIPartnersService } from './aPIPartners.service';
export * from './processController.service';
import { ProcessControllerService } from './processController.service';
export * from './roleAPI.service';
import { RoleAPIService } from './roleAPI.service';
export * from './transactionAPI.service';
import { TransactionAPIService } from './transactionAPI.service';
export * from './transactionCategoryAPI.service';
import { TransactionCategoryAPIService } from './transactionCategoryAPI.service';
export * from './transactionTypeAPI.service';
import { TransactionTypeAPIService } from './transactionTypeAPI.service';
export * from './uSERAPI.service';
import { USERAPIService } from './uSERAPI.service';
export const APIS = [APIAuthenticationService, APIFileStorageService, APIPartnersService, ProcessControllerService, RoleAPIService, TransactionAPIService, TransactionCategoryAPIService, TransactionTypeAPIService, USERAPIService];
