/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttachmentsRequest { 
    file_type?: string;
    file_path?: string;
    uploaded_at?: string;
    file_size?: number;
    key?: string;
    file_name?: string;
}

