/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityAttachmentInfo } from './entityAttachmentInfo';


export interface AttachmentResponse { 
    attachmentId?: string;
    fileName?: string;
    fileType?: string;
    filePath?: string;
    key?: string;
    uploadedAt?: string;
    fileSize?: number;
    attachedEntities?: Array<EntityAttachmentInfo>;
    attached?: boolean;
}

