/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Attachments { 
    attachmentId?: string;
    fileType?: string;
    filePath?: string;
    fileSize?: number;
    key?: string;
    uploadedAt?: string;
    fileName?: string;
}

