/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Partners { 
    partnerId?: string;
    name?: string;
    type?: string;
    email?: string;
    phone?: string;
    address?: string;
    createdAt?: string;
}

