/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    username?: string;
    password?: string;
    fullName?: string;
    email?: string;
    role_id?: string;
    status?: string;
}

