/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionResponse } from './transactionResponse';


export interface ResponseTransactionResponse { 
    code?: number;
    message?: string;
    data?: TransactionResponse;
}

