/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionCategory } from './transactionCategory';


export interface ResponseListTransactionCategory { 
    code?: number;
    message?: string;
    data?: Array<TransactionCategory>;
}

