/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';


export interface ResponseListTransactionType { 
    code?: number;
    message?: string;
    data?: Array<TransactionType>;
}

