/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';


export interface TransactionCategory { 
    transactionCategoryId?: string;
    transactionType?: TransactionType;
    code?: string;
    name?: string;
    description?: string;
    requireContract?: boolean;
    requireInvoice?: boolean;
    approvalLevel?: number;
}

