/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Partners } from './partners';
import { User } from './user';
import { TransactionCategory } from './transactionCategory';


export interface Transactions { 
    transactionId?: string;
    processId?: string;
    transactionCode?: string;
    transactionCategory?: TransactionCategory;
    createdBy?: User;
    createdAt?: string;
    updatedAt?: string;
    amount?: number;
    currencyType?: string;
    partner?: Partners;
    paymentType?: string;
    purposeDetail?: string;
    processStat?: string;
    note?: string;
}

