/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionRequest { 
    createdBy?: string;
    partnerId?: string;
    transactionCategoryId?: string;
    amount?: number;
    currencyType?: string;
    paymentType?: string;
    purposeDetail?: string;
    note?: string;
    attachmentIds?: Array<string>;
}

