/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Partners } from './partners';
import { TransactionCategory } from './transactionCategory';
import { Attachments } from './attachments';


export interface TransactionResponse { 
    transactionId?: string;
    transactionCode?: string;
    processId?: string;
    createdBy?: string;
    partner?: Partners;
    transactionCategory?: TransactionCategory;
    amount?: number;
    currencyType?: string;
    paymentType?: string;
    purposeDetail?: string;
    processStat?: string;
    note?: string;
    createdAt?: string;
    updatedAt?: string;
    attachmentsList?: Array<Attachments>;
}

